eureka:
  instance:
    prefer-ip-address: false # Changed from true
  client:
    # This should already be in your file and is correct
    serviceUrl:
      defaultZone: http://service-discovery-container:8761/eureka/

features:
  newSearchAlgorithm:
    enabled: true 
  anotherFeature:
    enabled: true # Example of another feature
