eureka:
  instance:
    prefer-ip-address: false 
    hostname: product-service
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/

features:
  newSearchAlgorithm:
    enabled: false
