eureka:
  instance:
    prefer-ip-address: false 
    hostname: product-service-container
  client:
    serviceUrl:
      defaultZone: http://service-discovery-container:8761/eureka/

features:
  newSearchAlgorithm:
    enabled: true 
  anotherFeature:
    enabled: true # Example of another feature
